<?xml version="1.0"?>
<robot name="smartcar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Robot Parameters from first file -->
  <xacro:property name="wheel_diameter" value="0.064"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheelbase_length" value="0.257"/>
  <xacro:property name="wheelbase_width" value="0.17"/>

  <!-- Base Link -->
  <link name="base_link" />

  <!-- Chassis Link -->
  <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${wheelbase_length} ${wheelbase_width} 0.05"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${wheelbase_length} ${wheelbase_width} 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.2" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 0.025" rpy="0 0 0"/>
  </joint>

  <!-- IMU Link -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="green">
        <color rgba="0.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </joint>

  <!-- Wheel Links -->
  <!-- Back Left Wheel -->
  <link name="back_left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="back_left_wheel_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="back_left_wheel_link"/>
    <origin xyz="-0.1285 ${wheelbase_width/2 + wheel_width/2} 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="100"/>
  </joint>

  <!-- Back Right Wheel -->
  <link name="back_right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="back_right_wheel_joint" type="continuous">
    <parent link="chassis_link"/>
    <child link="back_right_wheel_link"/>
    <origin xyz="-0.1285 -${wheelbase_width/2 + wheel_width/2} 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="100"/>
  </joint>

  <!-- Front Wheels with Steering -->
  <!-- Front Left Wheel Mount -->
  <link name="front_left_wheel_mount">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </collision>
  </link>

  <joint name="front_left_wheel_steer_joint" type="revolute">
    <parent link="chassis_link"/>
    <child link="front_left_wheel_mount"/>
    <origin xyz="0.1285 ${wheelbase_width/2 + wheel_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="100" velocity="100"/>
  </joint>

  <link name="front_left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="front_left_wheel_mount"/>
    <child link="front_left_wheel_link"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="100"/>
  </joint>

  <!-- Front Right Wheel Mount -->
  <link name="front_right_wheel_mount">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.01"/>
      </geometry>
    </collision>
  </link>

  <joint name="front_right_wheel_steer_joint" type="revolute">
    <parent link="chassis_link"/>
    <child link="front_right_wheel_mount"/>
    <origin xyz="0.1285 -${wheelbase_width/2 + wheel_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="100" velocity="100"/>
  </joint>

  <link name="front_right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="front_right_wheel_mount"/>
    <child link="front_right_wheel_link"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="100"/>
  </joint>

  <!-- LIDAR Link -->
  <link name="sllidar_base_link">
    <visual>
      <geometry>
        <cylinder radius="0.03" length="0.1"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.002"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="sllidar_base_link"/>
    <origin xyz="0.1285 0 0.1" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo plugins -->
  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <robotNamespace>/</robotNamespace>
      <joint_name>back_right_wheel_joint</joint_name>
      <joint_name>back_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_joint</joint_name>
      <joint_name>front_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_steer_joint</joint_name>
      <joint_name>front_left_wheel_steer_joint</joint_name>
      <alwaysOn>true</alwaysOn>
      <updateRate>50</updateRate>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="car_gazebo_plugin" filename="libcar_gazebo_plugin.so">
      <back_left_wheel_joint>back_left_wheel_joint</back_left_wheel_joint>
      <back_right_wheel_joint>back_right_wheel_joint</back_right_wheel_joint>
      <front_left_wheel_steer_joint>front_left_wheel_steer_joint</front_left_wheel_steer_joint>
      <front_left_wheel_joint>front_left_wheel_joint</front_left_wheel_joint>
      <front_right_wheel_steer_joint>front_right_wheel_steer_joint</front_right_wheel_steer_joint>
      <front_right_wheel_joint>front_right_wheel_joint</front_right_wheel_joint>
      <updateRate>50.0</updateRate>
    </plugin>
  </gazebo>

  <!-- LIDAR Plugin -->
  <gazebo reference="sllidar_base_link">
    <sensor type="ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>12</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
      <plugin name="lidar_plugin" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>sllidar_base_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <!-- IMU Plugin -->
  <gazebo reference="imu_link">
    <sensor type="imu" name="imu_sensor">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=imu_data</remapping>
        </ros>
      </plugin>
    </sensor>
  </gazebo>

</robot>